sudo: required
dist: xenial 
language: cpp

services:
  - docker

before_install:
  - ls
  # - docker pull coderus/sailfishos-platform-sdk:2.2.1.18        
  # - docker run -it --mount type=bind,source="$(pwd)",target=/home/nemo/QRail-git -d --name build-engine coderus/sailfishos-platform-sdk:2.2.1.18 /bin/bash  
  # - docker exec build-engine sb2 -t SailfishOS-2.2.1.18-armv7hl -m sdk-install -R zypper --non-interactive install git qt5-qtpositioning-devel qt5-qtsql-devel qt5-qtconcurrent-devel qt5-qttest-devel
  # - docker exec build-engine sb2 -t SailfishOS-2.2.1.18-i486 -m sdk-install -R zypper --non-interactive install git qt5-qtpositioning-devel qt5-qtsql-devel qt5-qtconcurrent-devel qt5-qttest-devel
  # - docker exec build-engine ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts  
  - docker pull dylanvanassche/qt5:bionic 
  - docker run -it --mount type=bind,source="$(pwd)",target=/home/user/QRail-git -d --name desktop-engine dylanvanassche/qt5:bionic /bin/bash # Qt 5.6 and higher

script:
  # Desktop x64 Qt 5.9.5 build + tests
  - docker exec desktop-engine bash -c "cd /home/user
    && cp -r QRail-git QRail-desktop
    && cd QRail-desktop
    && qmake CONFIG+=debug CONFIG+=qml_debug
    && make -j2
    && cd tests
    && qmake CONFIG+=debug CONFIG+=qml_debug
    && make -j2
    && ./qrail-tests"
  
  # Sailfish OS 2.2.1.18 Qt 5.6.3 ARMv7hl build + tests
  #- docker exec build-engine bash -c "cd /home/nemo
  #  && cp -r QRail-git QRail-armv7hl 
  #  && cd QRail-armv7hl 
  #  && sb2 -t SailfishOS-2.2.1.18-armv7hl -m sdk-build qmake CONFIG+=debug CONFIG+=qml_debug
  #  && sb2 -t SailfishOS-2.2.1.18-armv7hl -m sdk-build make -j2 
  #  && cd tests 
  #  && sb2 -t SailfishOS-2.2.1.18-armv7hl -m sdk-build qmake CONFIG+=debug CONFIG+=qml_debug 
  #  && sb2 -t SailfishOS-2.2.1.18-armv7hl -m sdk-build make -j2 
  #  && sb2 -t SailfishOS-2.2.1.18-armv7hl -m sdk-build ./qrail-tests"

  # Sailfish OS 2.2.1.18 Qt 5.6.3 i486 build + tests
  # - docker exec build-engine bash -c "cd /home/nemo
  #  && cp -r QRail-git QRail-i486 
  #  && cd QRail-i486
  #  && sb2 -t SailfishOS-2.2.1.18-i486 -m sdk-build qmake CONFIG+=debug CONFIG+=qml_debug
  #  && sb2 -t SailfishOS-2.2.1.18-i486 -m sdk-build make -j2 
  #  && cd tests 
  # && sb2 -t SailfishOS-2.2.1.18-i486 -m sdk-build qmake CONFIG+=debug CONFIG+=qml_debug 
  # && sb2 -t SailfishOS-2.2.1.18-i486 -m sdk-build make -j2 
  #  && sb2 -t SailfishOS-2.2.1.18-i486 -m sdk-build ./qrail-tests"
  
